### ISSUE TITLE
Make rules evaluation conditional to a certain date range

### ISSUE THREAD

**Issue by aitrusgit** [bluealba/rules-js#13]
It would be a good idea to natively support date range conditions for rules, similar to drools `date-effective` and `date-expires`

https://docs.jboss.org/drools/release/5.2.0.Final/drools-expert-docs/html/ch05.html

**Comment by clombardi** [comment]
I added a new built-in condition called `dateRange`. Incorporated into master by the commit c0111e02a45112de193d08fe6633ca024a41ef90 .
